- hosts: local
  gather_facts: false
  name: Import tasks
  tasks:
    - import_tasks: tasks.yml
    - import_tasks: tasks.yml

- hosts: local
  gather_facts: false
  name: Include tasks
  tasks:
    - include_tasks: tasks.yml
    - include_tasks: tasks.yml
